export const CHAT_LIST_ITEM = `CHAT_LIST_ITEM`
export const CHAT_LIST_BUBBLE = `CHAT_LIST_BUBBLE`
export const SOCKET_CHAT_MES = {
   GET_LIST_MESSAGES: "GET_LIST_MESSAGES",
   JOIN_ROOM: "JOIN_ROOM",
   LEAVE_ROOM: "LEAVE_ROOM",
   SEND_MESSAGE: "SEND_MESSAGE",
   RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
};
