import Provider from "@/components/provider/Provider";
import { TITLE } from "@/constant/app.constant";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import type { Metadata, Viewport } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Geist, Geist_Mono, Great_Vibes, Quicksand } from "next/font/google";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

const quicksand = Quicksand({
   subsets: ["vietnamese"],
   variable: "--font-quicksand",
});

const greatVibes = Great_Vibes({
   variable: "--font-great-vibes",
   subsets: ["vietnamese"],
   weight: ["400"],
});

export const viewport: Viewport = {
   width: "device-width",
   initialScale: 1,
};

export const metadata = async (): Promise<Metadata> => {
   // const logoUrl = await getSiteLogo();
   return {
      title: TITLE,
      description: "Generated by create next app",
      keywords: ["ecommerce", "online shopping", "stores", "products", "shop online", "buy online", "electronics", "clothing", "home goods"],
      authors: [{ name: "TMDT Platform" }],
      icons: {
         icon: `/logo/logo-nail.webp`,
         apple: `/logo/logo-nail.webp`,
      },
      openGraph: {
         title: "TMDT - Online Shopping Platform",
         description: "Explore thousands of stores and products. Log in to make secure purchases on our eCommerce platform.",
         url: "https://tmdt.vulebaolong.com",
         type: "website",
         images: [
            {
               url: `/logo/logo-nail.webp`,
               width: 800,
               height: 600,
               alt: "Site logo",
            },
         ],
      },
      twitter: {
         card: "summary_large_image",
         title: "TMDT - Online Shopping Platform",
         description: "Browse stores and products with ease. Log in to buy securely.",
         images: [`/logo/logo-nail.webp`],
      },
   };
};

type TProps = {
   children: React.ReactNode;
};

export default async function RootLayout({ children }: TProps) {
   const locale = await getLocale();
   const messages = await getMessages();

   return (
      <html lang={locale} {...mantineHtmlProps} suppressHydrationWarning>
         <head>
            <ColorSchemeScript />
         </head>
         <body className={`${geistSans.variable} ${geistMono.variable} ${quicksand.variable} ${greatVibes.variable} antialiased`}>
            <NextIntlClientProvider messages={messages}>
               <Provider>{children}</Provider>
            </NextIntlClientProvider>
         </body>
      </html>
   );
}
