import { getSiteLogo } from "@/actions/setting.action";
import Provider from "@/components/provider/Provider";
import { TITLE } from "@/constant/app.constant";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import type { Metadata, Viewport } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const viewport: Viewport = {
   width: "device-width",
   initialScale: 1,
};

export const metadata = async (): Promise<Metadata> => {
   const logoUrl = await getSiteLogo();
   return {
      title: TITLE,
      description: "Generated by create next app",
      keywords: ["ecommerce", "online shopping", "stores", "products", "shop online", "buy online", "electronics", "clothing", "home goods"],
      authors: [{ name: "TMDT Platform" }],
      icons: {
         icon: logoUrl,
         apple: logoUrl,
      },
      openGraph: {
         title: "TMDT - Online Shopping Platform",
         description: "Explore thousands of stores and products. Log in to make secure purchases on our eCommerce platform.",
         url: "https://tmdt.vulebaolong.com",
         type: "website",
         images: [
            {
               url: logoUrl,
               width: 800,
               height: 600,
               alt: "Site logo",
            },
         ],
      },
      twitter: {
         card: "summary_large_image",
         title: "TMDT - Online Shopping Platform",
         description: "Browse stores and products with ease. Log in to buy securely.",
         images: [logoUrl],
      },
   };
};

type TProps = {
   children: React.ReactNode;
};

export default async function RootLayout({ children }: TProps) {
   const locale = await getLocale();
   const messages = await getMessages();

   return (
      <html lang={locale} {...mantineHtmlProps} suppressHydrationWarning>
         <head>
            <ColorSchemeScript />
         </head>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <NextIntlClientProvider messages={messages}>
               <Provider>{children}</Provider>
            </NextIntlClientProvider>
         </body>
      </html>
   );
}

// https://sepay.vn/lap-trinh-cong-thanh-toan.html
// https://www.notion.so/SEPAY-1c398db6991280d49ea1e111620a1261

// ssh tmdt_ctid@207.2.122.125
// - IP: 207.2.122.125
// - Port: 22
// - Username: tmdt_ctid
// - Password: 123456a@A
