name: CD docker

on:
   workflow_run:
      workflows: ["CI docker"]
      types:
         - completed

jobs:
   build:
      runs-on: tmdt

      if: ${{ github.event.workflow_run.conclusion == 'success' }}

      steps:
         - name: Delete old .env file
           run: rm -f .env || true

         - name: Create new .env file and add environment variables
           run: |
              echo "MONGODB_URI=${{secrets.MONGODB_URI}}" >> .env
              echo "ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}" >> .env
              echo "ACCESS_TOKEN_EXPIRES=${{secrets.ACCESS_TOKEN_EXPIRES}}" >> .env
              echo "REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}}" >> .env
              echo "REFRESH_TOKEN_EXPIRES=${{secrets.REFRESH_TOKEN_EXPIRES}}" >> .env
              echo "CLOUDINARY_NAME=${{secrets.CLOUDINARY_NAME}}" >> .env
              echo "CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}}" >> .env
              echo "CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}}" >> .env
              echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" >> .env
              echo "GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}" >> .env

         - name: Stop running containers
           run: docker stop cons-tmdt || true

         - name: Remove containers
           run: docker rm cons-tmdt || true

         - name: Delete old docker image
           run: docker rmi vulebaolong/img-tmdt:latest || true

         - name: Pull Docker image
           run: docker pull vulebaolong/img-tmdt:latest || true

         - name: Run Docker
           run: |
              docker run -d \
              --env-file .env \
              -p 3069:3000 \
              --name cons-tmdt \
              vulebaolong/img-tmdt:latest
