name: CI docker

on:
   push:
      branches: ["main"]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4

         - name: Login Dockerhub
           run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

         - name: Remove old build files
           run: rm -rf .next node_modules

         - name: Build the Docker image
           run: |
              docker build \
              --build-arg MONGODB_URI=${{secrets.MONGODB_URI}} \
              --build-arg ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}} \
              --build-arg ACCESS_TOKEN_EXPIRES=${{secrets.ACCESS_TOKEN_EXPIRES}} \
              --build-arg REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}} \
              --build-arg REFRESH_TOKEN_EXPIRES=${{secrets.REFRESH_TOKEN_EXPIRES}} \
              --build-arg CLOUDINARY_NAME=${{secrets.CLOUDINARY_NAME}} \
              --build-arg CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}} \
              --build-arg CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}} \
              --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID}} \
              --build-arg GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}} \
              -t vulebaolong/img-tmdt:latest .

         - name: Push to DockerHub
           run: docker push vulebaolong/img-tmdt:latest
