name: CI docker

on:
   push:
      branches: ["main"]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4

         - name: Login Dockerhub
           run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

         - name: Remove old build files
           run: rm -rf .next node_modules

         - name: Delete old .env file
           run: rm -f .env || true

         - name: Create new .env file and add environment variables
           run: |
              echo "MONGODB_URI=${{secrets.MONGODB_URI}}" >> .env
              echo "ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}" >> .env
              echo "ACCESS_TOKEN_EXPIRES=${{secrets.ACCESS_TOKEN_EXPIRES}}" >> .env
              echo "REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}}" >> .env
              echo "REFRESH_TOKEN_EXPIRES=${{secrets.REFRESH_TOKEN_EXPIRES}}" >> .env
              echo "CLOUDINARY_NAME=${{secrets.CLOUDINARY_NAME}}" >> .env
              echo "CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}}" >> .env
              echo "CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}}" >> .env
              echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID}}" >> .env
              echo "GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}" >> .env

         - name: Build the Docker image
           run: docker build --env-file .env -t vulebaolong/img-tmdt:latest .

         - name: Push to DockerHub
           run: docker push vulebaolong/img-tmdt:latest
