name: CI docker

on:
   push:
      branches: ["main"]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4

         - name: Login Dockerhub
           run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

         - name: Remove old build files
           run: rm -rf .next node_modules

         - name: Build the Docker image
           run: docker build --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }} -t vulebaolong/img-tmdt:latest .

         - name: Push to DockerHub
           run: docker push vulebaolong/img-tmdt:latest
