name: CI docker

on:
   push:
      branches: ["main"]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4

         - name: Login Dockerhub
           run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

         - name: Build the Docker image
           run: docker build -t vulebaolong/img-tmdt:latest .

         - name: Push to DockerHub
           run: docker push vulebaolong/img-tmdt:latest
